# API Testing
GET https://tugas3-tcc-be-rezarasendriya-805193520.us-central1.run.app/ HTTP/1.1

###
# GET : All Notes dari Cloud SQL
GET https://tugas3-tcc-be-rezarasendriya-805193520.us-central1.run.app/api/v1/notes HTTP/1.1
Content-Type: application/json

###
# GET : Note by ID
GET https://tugas3-tcc-be-rezarasendriya-805193520.us-central1.run.app/api/v1/notes/2 HTTP/1.1
Content-Type: application/json

###
# POST : Create Note baru ke Cloud SQL
POST https://tugas3-tcc-be-rezarasendriya-805193520.us-central1.run.app/api/v1/notes HTTP/1.1
Content-Type: application/json

{
  "judul": "Tugas 3 PaaS",
  "isi": "Berhasil deploy ke Cloud Run dan simpan ke Cloud SQL."
}

###
# PUT : Update Note berdasarkan ID
PUT https://tugas3-tcc-be-rezarasendriya-805193520.us-central1.run.app/api/v1/notes/2 HTTP/1.1
Content-Type: application/json

{
  "judul": "Belajar TCC ",
  "isi": "Belajar PaaS dengan Google Cloud Platform."
}

###
# DELETE : Delete Note berdasarkan ID
DELETE https://tugas3-tcc-be-rezarasendriya-805193520.us-central1.run.app/api/v1/notes/4 HTTP/1.1
Content-Type: application/json