steps:
  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Build project
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

  # Deploy ke App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'gcloud app deploy'

timeout: '1600s'
options:
  logging: CLOUD_LOGGING_ONLY